### ISSUE TITLE
the same code？

### ISSUE THREAD

**Issue by zhaolongkzz** [TianhongDai/reinforcement-learning-algorithms#3]
Thanks for your code for DRL. But I find the `dueling_agent.py` of dueling dqn is the same as `ddqn_agent.py` of double dqn. So where do you implement the dueling dqn algorithm into code?

**Comment by TianhongDai** [comment]
Hi, the difference between the Double DQN and Dueling DQN is in the network architecture - So, there's no difference between the file `dueling_agent.py` and `ddqn_agent.py`. The only difference is in the `models.py`: https://github.com/TianhongDai/reinforcement-learning-algorithms/blob/master/03-dueling-network/models.py#L31 

And also thanks for your issues. i think I should make DQN, Double DQN and Dueling DQN into one code, and they can be selected by using different Flags. Thanks!
